# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install \
          -r requirements/requirements.txt \
          -r requirements/requirements.dev.txt \
          -r requirements/requirements.types.txt
    - name: Reformat with black
      run: |
        python3 -m black .
    - name: Type check with mypy
      run: |
        python3 -m mypy .
    - name: Test with coverage/unittest
      run: |
        coverage run -m unittest discover .
        coverage report -m --skip-covered
